package adventofcode2016;

public class Day2 {
	final static String INPUT = "LLRRLLRLDDUURLLRDUUUDULUDLUULDRDDDULLLRDDLLLRRDDRRUDDURDURLRDDULRRRLLULLULLRUULDLDDDUUURRRRURURDUDLLRRLDLLRRDRDLLLDDRRLUDDLDDLRDRDRDDRUDDRUUURLDUDRRLULLLDRDRRDLLRRLDLDRRRRLURLLURLRDLLRUDDRLRDRRURLDULURDLUUDURLDRURDRDLULLLLDUDRLLURRLRURUURDRRRULLRULLDRRDDDULDURDRDDRDUDUDRURRRRUUURRDUUDUDDDLRRUUDDUUDDDUDLDRDLRDUULLRUUDRRRDURLDDDLDLUULUDLLRDUDDDDLDURRRDRLLRUUUUDRLULLUUDRLLRDLURLURUDURULUDULUDURUDDULDLDLRRUUDRDDDRLLRRRRLDRRRD\n"
			+ "DRRRDULLRURUDRLRDLRULRRLRLDLUDLUURUUURURULRLRUDRURRRLLUDRLLDUDULLUUDLLUUUDDRLRUDDDDLDDUUDULDRRRDULUULDULDRUUULRUDDDUDRRLRLUDDURLLDRLUDUDURUUDRLUURRLUUUDUURUDURLUUUDRDRRRDRDRULLUURURDLUULLDUULUUDULLLDURLUDRURULDLDLRDRLRLUURDDRLDDLRRURUDLUDDDLDRLULLDRLLLURULLUURLUDDURRDDLDDDDRDUUULURDLUUULRRLRDLDRDDDRLLRUDULRRRUDRRLDRRUULUDDLLDUDDRLRRDLDDULLLRDURRURLLULURRLUULULRDLULLUUULRRRLRUDLRUUDDRLLLLLLLURLDRRUURLDULDLDDRLLLRDLLLDLRUUDRURDRDLUULDDRLLRRURRDULLULURRDULRUDUDRLUUDDDDUULDDDUUDURLRUDDULDDDDRUULUUDLUDDRDRD\n"
			+ "RRRULLRULDRDLDUDRRDULLRLUUDLULLRUULULURDDDLLLULRURLLURUDLRDLURRRLRLDLLRRURUDLDLRULDDULLLUUDLDULLDRDLRUULDRLURRRRUDDLUDLDDRUDDUULLRLUUDLUDUDRLRUULURUDULDLUUDDRLLUUURRURUDDRURDLDRRDRULRRRRUUUDRDLUUDDDUDRLRLDRRRRUDDRLLRDRLUDRURDULUUURUULLRDUUULRULRULLRULRLUDUDDULURDDLLURRRULDRULDUUDDULDULDRLRUULDRDLDUDRDUDLURLLURRDLLDULLDRULDLLRDULLRURRDULUDLULRRUDDULRLDLDLLLDUDLURURRLUDRRURLDDURULDURRDUDUURURULLLUDDLDURURRURDDDRRDRURRUURRLDDLRRLDDULRLLLDDUDRULUULLULUULDRLURRRLRRRLDRRLULRLRLURDUULDDUDLLLUURRRLDLUDRLLLRRUU\n"
			+ "URLDDDLDRDDDURRRLURRRRLULURLDDUDRDUDDLURURLLRDURDDRLRUURLDLLRDLRUUURLRLDLDRUDDDULLDULLDUULURLDRDUDRRLRRLULRDDULUDULDULLULDLRRLRRLLULRULDLLDULRRLDURRRRDLURDLUDUUUDLURRRRRUDDUDUUDULDLURRDRLRLUDUDUUDULDDURUDDRDRUDLRRUDRULDULRDRLDRUDRLLRUUDDRLURURDRRLRURULLDUUDRDLULRUULUDURRULLRLUUUUUDULRLUUDRDUUULLULUDUDDLLRRLDURRDDDLUDLUUDULUUULDLLLLUUDURRUDUDLULDRRRULLLURDURDDLRRULURUDURULRDRULLRURURRUDUULRULUUDDUDDUURLRLURRRRDLULRRLDRRDURUDURULULLRUURLLDRDRURLLLUUURUUDDDLDURRLLUUUUURLLDUDLRURUUUDLRLRRLRLDURURRURLULDLRDLUDDULLDUDLULLUUUDLRLDUURRR\n"
			+ "RLLDRDURRUDULLURLRLLURUDDLULUULRRRDRLULDDRLUDRDURLUULDUDDDDDUDDDDLDUDRDRRLRLRLURDURRURDLURDURRUUULULLUURDLURDUURRDLDLDDUURDDURLDDDRUURLDURRURULURLRRLUDDUDDDLLULUDUUUDRULLLLULLRDDRDLRDRRDRRDLDLDDUURRRDDULRUUURUDRDDLRLRLRRDLDRDLLDRRDLLUULUDLLUDUUDRDLURRRRULDRDRUDULRLLLLRRULDLDUUUURLDULDDLLDDRLLURLUDULURRRUULURDRUDLRLLLRDDLULLDRURDDLLDUDRUDRLRRLULLDRRDULDLRDDRDUURDRRRLRDLDUDDDLLUDURRUUULLDRLUDLDRRRRDDDLLRRDUURURLRURRDUDUURRDRRUDRLURLUDDDLUDUDRDRURRDDDDRDLRUDRDRLLDULRURULULDRLRLRRLDURRRUL\n";

	/**
	 * <pre>
	 * 1 2 3
	 * 4 5 6 
	 * 7 8 9
	 * </pre>
	 */
	static int mapping1[][] = new int[][] {
		//@formatter:off
		// u, r, d, l 
		{1,2,4,1},
		{2,3,5,1},
		{3,3,6,2},
		{1,5,7,4},
		{2,6,8,4},
		{3,6,9,5},
		{4,8,7,7},
		{5,9,8,7},
		{6,9,9,8},
		//@formatter:on
	};

	/**
	 * <pre>
	 *     1
	 *   2 3 4
	 * 5 6 7 8 9
	 *   A B C
	 *     D
	 * </pre>
	 */
	static int mapping2[][] = new int[][] {
		//@formatter:off
		// u, r, d, l 
		{1,1,3,1},
		{2,3,6,2},
		{1,4,7,2},
		{4,4,8,3},
		{5,6,5,5},
		{2,7,0xa,5},
		{3,8,0xb,6},
		{4,9,0xc,7},
		{9,9,9,8},
		{6,0xb,0xa,0xa},
		{7,0xc,0xd,0xa},
		{8,0xc,0xc,0xb},
		{0xb,0xd,0xd,0xd},
		//@formatter:on
	};

	public static void main(String[] args) {
		String[] lines = INPUT.split("\n");
		int finalKey = 5;
		System.out.println("Day1:");
		for (var line : lines) {
			finalKey = followDirections(mapping1, finalKey, line.toCharArray());
			System.out.print(" " + Integer.toHexString(finalKey));
		}
		System.out.println();

		finalKey = 5;
		System.out.println("Day2:");
		for (var line : lines) {
			finalKey = followDirections(mapping2, finalKey, line.toCharArray());
			System.out.print(" " + Integer.toHexString(finalKey));
		}
		System.out.println();

	}

	public static int followDirections(int[][] mapping, int startKey, char[] charArray) {
		int key = startKey;
		for (char c : charArray) {
			//@formatter:off
			int offset =  c == 'U' ? 0 
						: c == 'R' ? 1
						: c == 'D' ? 2
						: c == 'L' ? 3
						: 100;
			//@formatter:on
			key = mapping[key - 1][offset];
		}
		return key;
	}
}
